### ISSUE TITLE
What GT depth is used for evaluation?

### ISSUE THREAD

**Issue by SwagJ** [hyBlue/FSRE-Depth#2]
Hi @hyBlue , 

Thank you for your great work. I just have one question regarding to the GT depth used for evaluation. 
In your dataloader, you load gt_depth from file. 
 (https://github.com/hyBlue/FSRE-Depth/blob/d746866965204c37a072f3518dfd873df7ed2f1a/datasets/kitti_dataset.py#L84).
However, in your evaluation code, gt_depth is loaded from an npz file. 
(https://github.com/hyBlue/FSRE-Depth/blob/d746866965204c37a072f3518dfd873df7ed2f1a/evaluate_depth.py#L148)
And the gt_depth from dataloader is not used?

Is this true?

Also, for the gt_depth from npz, this gt_depth is corresponding to the groundtruth set of KITTI Depth Prediction or velodyne_raw set of KITTI Depth Prediction?

Thank you in advance. 

Best,

**Comment by hyBlue** [comment]
Hi, thanks for your interest. 
I'm sorry for missing instruction about it. You need to first export ground truth data as .npz file by running export_gt_depth.py.  You can find instructions about it in [Monodepth2](https://github.com/nianticlabs/monodepth2). Thanks

**Comment by SwagJ** [comment]
@hyBlue，Thank you very much for your information. I will look it up!

**Comment by SwagJ** [comment]
Hi @hyBlue, 

Just have one question. Which split is used for reporting the result of Table 1.a in your paper, Eigen or Eigen-benchmark?
Thank you

**Comment by hyBlue** [comment]
HI, 
It's Eigen. You can evaluate it with default options. 
Thanks

**Comment by SwagJ** [comment]
Thank you for your reply. It is crystal clear now.
