### ISSUE TITLE
Question About Error Map Generation in the paper

### ISSUE THREAD

**Issue by SwagJ** [hyBlue/FSRE-Depth#3]
Hi @hyBlue, 

What method did you use to handle discoutinuity of GT depth when plotting the error map in your paper? Did you use interpolation? Since GT depth map inevitably has empty pixel, I am just wondering about this. 
In addition, I think there is a bug in your evaluation code in your current implementation. 

https://github.com/hyBlue/FSRE-Depth/blob/d746866965204c37a072f3518dfd873df7ed2f1a/evaluate_depth.py#L68
the dataset doesn't have input: fix_K. 

So, I am looking forward to your reply on error map part. Thank you in advance. 

Best,

**Comment by hyBlue** [comment]
Hi, 
we evaluated error map by using the prediction of pretrained supervised depth network. This is mentioned in page 7 as a footnote. 

fix_K: it seems to be a bug that occurred when I cleaned up my code. Maybe you can just remove it and run the evaluation. 

Thanks

**Comment by SwagJ** [comment]
@hyBlue， 

Thank you for your reply. I apologize for overlook the footnote. 

Best,
