### ISSUE TITLE
error in code (train and test)

### ISSUE THREAD

**Issue by jjinCode** [hyBlue/FSRE-Depth#5]
Hi,

I try to train and test your model.
I found some error in your code.

1. '--data_path' option 
-> when I set --data_path for my own dataset path, the path that your code modified was pointed to wrong directory
2. when I run 'evaluate_depth.py' for tersting, 
2-1. '--fix_K' option does not exist in KittiDataset class
2-2. in 111 line, output = models['depth'](features, mode='depth'), return error => forward() got an unexpected keyword argument 'mode'

I hope to use your official evaluate code / script.

Thanks!

**Comment by hyBlue** [comment]
Hi,  thank you for your interest in our work. I'm sorry for the bugs in the code.  

For Q1,  Maybe you should add 'data_path=self.opt.data_path' argument below to prevent the KittiDataset objects from using the default data path.
https://github.com/hyBlue/FSRE-Depth/blob/d746866965204c37a072f3518dfd873df7ed2f1a/train_ddp.py#L56-L65

For Q2, you can just remove 'fix_K' and 'mode' there. They're just the legacy codes that still remain. I'm sorry for them.

**Comment by jjinCode** [comment]
Thanks for reply!

I changed the evaluation code according to your advice and it works well~
