### ISSUE TITLE
Explanation of the sgementation dataset

### ISSUE THREAD

**Issue by CUMTchenlv** [hyBlue/FSRE-Depth#7]
Hi
    Thank you for a great job. Could you tell me how the sgementation  dataset is obtained? Is it used to train semantic segmentation subnetworks ？   Thank you very much.

**Comment by hyBlue** [comment]
Hi, I'm sorry for the late response. 
The segmentation labels are computed from the off-the-shelf [segmentation network](https://github.com/NVIDIA/semantic-segmentation/tree/sdcnet). This is described in Section 3.1.2 in the paper and Section C.1 in the supplementary. 
Thanks!
