### ISSUE TITLE
UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.

### ISSUE THREAD

**Issue by lonelysheeep** [hyBlue/FSRE-Depth#9]
when i run evaluate_depth 
/home/shs/miniconda3/envs/shs/lib/python3.7/site-packages/torchvision/transforms/transforms.py:334: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "

**Comment by hyBlue** [comment]
Hi, thank you for your notice. The warning may depend on the torch version but will not affect results.
